version: '3.4'

services:
  projektvs2:
    image: projektvs2:dev
    container_name: Projektvs2
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "Projektvs2"
    environment:
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - /Users/dusenkot/Projects/Projekt_OOP_w68139/Projektvs2:/app
      - /Users/dusenkot/Projects/Projekt_OOP_w68139:/src
      - /Users/dusenkot/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/dusenkot/.nuget/packages/:/root/.nuget/packages:ro
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net7.0/Projektvs2.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true